In [1]:
>>> import numpy as np
>>> from sklearn.model_selection import train_test_split
>>> X, y = np.arange(10).reshape((5, 2)), range(5)

In [2]:
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [3]:
y

range(0, 5)

In [5]:
list(y)

[0, 1, 2, 3, 4]

In [6]:
list(X)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [7]:
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [8]:
y

range(0, 5)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [11]:
X_train

array([[4, 5],
       [0, 1],
       [6, 7]])

In [12]:
X_test

array([[2, 3],
       [8, 9]])

In [13]:
y_train

[2, 0, 3]

In [14]:
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])

In [15]:
np.ceil(a)

array([-1., -1., -0.,  1.,  2.,  2.,  2.])

In [16]:
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.1])

In [17]:
np.ceil(a)

array([-1., -1., -0.,  1.,  2.,  2.,  3.])

In [33]:
import pandas as pd

df = pd.DataFrame(np.arange(60).reshape(12,5),columns=['A', 'B', 'C', 'D', 'E'])

In [34]:
df

A   B   C   D   E
0    0   1   2   3   4
1    5   6   7   8   9
2   10  11  12  13  14
3   15  16  17  18  19
4   20  21  22  23  24
5   25  26  27  28  29
6   30  31  32  33  34
7   35  36  37  38  39
8   40  41  42  43  44
9   45  46  47  48  49
10  50  51  52  53  54
11  55  56  57  58  59

In [44]:
df = df.drop([0, 1], axis=0)
df = df.drop(['B', 'C'], axis=1)

In [45]:
df

A   D   E
2   10  13  14
3   15  18  19
4   20  23  24
5   25  28  29
6   30  33  34
7   35  38  39
8   40  43  44
9   45  48  49
10  50  53  54
11  55  58  59

In [35]:
df.describe()

A          B          C          D          E
count  12.000000  12.000000  12.000000  12.000000  12.000000
mean   27.500000  28.500000  29.500000  30.500000  31.500000
std    18.027756  18.027756  18.027756  18.027756  18.027756
min     0.000000   1.000000   2.000000   3.000000   4.000000
25%    13.750000  14.750000  15.750000  16.750000  17.750000
50%    27.500000  28.500000  29.500000  30.500000  31.500000
75%    41.250000  42.250000  43.250000  44.250000  45.250000
max    55.000000  56.000000  57.000000  58.000000  59.000000